### ISSUE TITLE
When open keyboard, UITextfield doesn't scroll and visible

### ISSUE THREAD

**Issue by parmar-mehul** [hackiftekhar/IQKeyboardToolbarManager#1]
**Describe the bug**
Please make sure, UI scroll automatically, so that we can remove https://github.com/hackiftekhar/IQKeyboardManager, and only use https://github.com/hackiftekhar/IQKeyboardToolbarManager
But while only using IQKeyboardToolbarManage, without IQKeyboardManager, We expect IQKeyboardToolbarManage fulfil all good things from IQKeyboardManager, so that we can remove IQKeyboardManager and UI work and manage and scroll when we open keyboard by tap on UITextfield

**To Reproduce**
While using IQKeyboardToolbarManager,
1. enable library , IQKeyboardManager.shared.enable = true
2. Run app, Click on UITextfield,
3. Scroll to UITextfield doesn't happen
4. Unable to see UITextfield if it is in bottom of screen, visible keyboard open and textfield disappear behind it, unable to autoscroll

**Expected behavior**
While using https://github.com/hackiftekhar/IQKeyboardManager, When Keyboard visible, Scrollview scroll and move near to UITextfield, but while using https://github.com/hackiftekhar/IQKeyboardToolbarManager, Automatic Scroll doesn't happen.

**Screenshots** **Demo Project**
Try your self, Very easy to reproduce

### Versions
**Xcode:** Version 16.0 (16A242d)
**Mac OS:** 15.0.1 (24A348)
**Simulator/Device:** 18.1.0
**Simulator/Device Name:** iPhone 16 Pro
**Library Version:** 1.1.0

**Comment by hackiftekhar** [comment]
@parmar-mehul You should still use IQKeyboardManager for it's primary purpose. The primary purpose is to keep the distance between keyboard and textfield to make sure textfield is always visible.

The problem was that, IQKeyboardManager was taking much more responsibility than it's primary purpose
- Showing Toolbar with next/previous/done button.
- IQTextView class for placeholder textView.
- Keyboard Return key handling etc.

So features which were secondary purpose for the IQKeyboardManager has been moved to their own github libraries. One of them was IQKeyboardToolbarManager which took all the responsibility related to the toolbar handling.

So you should be using IQKeyboardManager for keeping keyboard and textfield distance, while you should be using IQKeyboardToolbarManager for showing toolbar in keyboard with next/previous/done buttons.

Hope this clear any confusions.

**Comment by hardikthakkar2208** [comment]
@hackiftekhar, when the text field is behind the keyboard it will create an issue, the text field/textview does not scroll automatically as before When you are free please check this issue.

Thanks

**Comment by hackiftekhar** [comment]
IQKeyboardToolbarManager is only responsible for toolbar related stuffs.
For maintaining textfield distance with keyboard, please use
IQKeyboardManager
